// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef ptiffUI_h
#define ptiffUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Fl_Image_Display.H"
#include <FL/Fl_Output.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_File_Chooser.H>
#include "util.h"

class ptiffUI {
public:
  ptiffUI();
  Fl_Double_Window *window_;
  Fl_Image_Display *display_;
  Fl_Output *filename_;
  Fl_Value_Slider *range_;
private:
  inline void cb_range__i(Fl_Value_Slider*, void*);
  static void cb_range_(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *offset_;
private:
  inline void cb_offset__i(Fl_Value_Slider*, void*);
  static void cb_offset_(Fl_Value_Slider*, void*);
public:
  Fl_Button *openfile_;
private:
  inline void cb_openfile__i(Fl_Button*, void*);
  static void cb_openfile_(Fl_Button*, void*);
public:
  Fl_Button *previous_;
private:
  inline void cb_previous__i(Fl_Button*, void*);
  static void cb_previous_(Fl_Button*, void*);
public:
  Fl_Button *next_;
private:
  inline void cb_next__i(Fl_Button*, void*);
  static void cb_next_(Fl_Button*, void*);
public:
  ~ptiffUI();
  void show();
  Fl_Shared_Image *Ifl;
};
#endif
